services:
  _defaults:
    autowire: true
    autoconfigure: true

  Berecont\ContaoLeafletsimpleBundle\:
    resource: ../src
    exclude: ../src/{ContaoManager,BerecontContaoLeafletsimpleBundle.php}